project_id = "rqgxjpyirxnanciwhcbz"

[functions.wonder-chat]
verify_jwt = false

[functions.wonder-tts]
verify_jwt = false

[functions.wonder-visuals]
verify_jwt = false

[functions.wonder-sfx]
verify_jwt = false
